/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Buttons from '../components/Buttons';
import Cards from '../components/Cards';
import Header from '../components/Header';

const siteStyles = css`
  background: url('/images/background-stars.svg');
  z-index: 1;
  min-height: 1024px;
`;

const mainStyles = css`
  .title {
    text-align: center;
    position: absolute;
    width: 263px;
    height: 104px;
    left: 925px;
    top: 212px;
    font-size: 80px;
    line-height: 104px;
    text-transform: uppercase;
    margin: 0;
  }

  .image {
    position: absolute;
    top: 328px;
    left: 335px;
  }

  .paragraph {
    position: absolute;
    width: 314.5px;
    /* height: 150px; */
    left: 925px;
    top: 339px;
    margin: 0;
    font-size: 14px;
    line-height: 179%;
  }

  .source {
    position: absolute;
    width: 164px;
    height: 25px;
    left: 925px;
    top: 480px;
    line-height: 25px;
  }
`;

export default function Earth() {
  return (
    <div css={siteStyles}>
      <Head>
        <title>Planets fact site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main css={mainStyles}>
        <Image
          className="image"
          src={'/images/planet-venus.svg'}
          width="290"
          height="290"
          alt="mercury"
        />
        <div>
          <h1 className="title">venus</h1>
          <p className="paragraph">
            Venus is the second planet from the Sun. It is named after the Roman
            goddess of love and beauty. As the brightest natural object in
            Earth&apos;s night sky after the Moon, Venus can cast shadows and
            can be, on rare occasions, visible to the naked eye in broad
            daylight.
          </p>
          <span className="source">
            Source :{' '}
            <a
              href="https://en.wikipedia.org/wiki/Venus"
              rel="noopener noreferrer"
              target="_blank"
            >
              Wikipedia
              <i className="sourceIcon" />
            </a>
          </span>
          <Buttons className="mercuryButtons" />
          <Cards />
        </div>
      </main>
    </div>
  );
}
