/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react';
import { League_Spartan } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

const spartanBold = League_Spartan({
  weight: '700',
  subset: ['latin'],
});

const buttonsStyles = css`
  display: flex;
  flex-direction: column;
  gap: 16px;
  position: absolute;
  width: 350px;
  height: 176px;
  left: 925px;
  top: 577px;
  text-transform: uppercase;

  button {
    width: 350px;
    height: 48px;
    mix-blend-mode: normal;
    // opacity: 0.2;
    border: 1px solid #38384f;
    color: #38384f;
    background-color: transparent;
    text-align: left;
    cursor: pointer;

    :hover {
      background-color: #38384f;
    }

    :active {
      background-color: #1ec1a2;
    }

    span {
      font-size: 12px;
      line-height: 25px;
      /* identical to box height, or 208% */

      letter-spacing: 2.57143px;
      text-transform: uppercase;

      margin-left: 25px;

      color: #ffffff;
    }

    .number {
      margin-left: 28px;
      margin-top: 12px;
    }
  }
`;

const siteStyles = css`
  background: url('/images/background-stars.svg');
  z-index: 1;
  min-height: 1024px;
`;

const mainStyles = css`
  .title {
    position: absolute;
    width: 263px;
    height: 104px;
    left: 925px;
    top: 212px;
    font-size: 80px;
    line-height: 104px;
    text-transform: uppercase;
    margin: 0;
  }

  .image {
    position: absolute;
    top: 328px;
    left: 335px;
  }

  .paragraph {
    position: absolute;
    width: 314.5px;
    /* height: 150px; */
    left: 925px;
    top: 339px;
    margin: 0;
    font-size: 14px;
    line-height: 179%;
  }

  .source {
    position: absolute;
    width: 164px;
    height: 25px;
    left: 925px;
    top: 480px;
    line-height: 25px;
  }
`;

const cardsStyles = css`
  display: flex;
  gap: 30px;
  position: absolute;
  left: 165px;
  top: 840px;

  .card {
    width: 255px;
    height: 128px;
    border: 1px solid #38384f;

    h4 {
      text-transform: uppercase;
      margin-left: 23px;
      margin-top: 20px;
      margin-bottom: 0;
    }

    h2 {
      text-transform: uppercase;
      font-size: 40px;
      margin: 0;
      /* margin-left: 23px;
      margin-top: 16px; */
      position: relative;
      left: 23px;
      top: 8px;
    }
  }
`;

export default function Uranus() {
  return (
    <div css={siteStyles}>
      <Head>
        <title>Earth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main css={mainStyles}>
        <Image
          className="image"
          src={'/images/planet-uranus.svg'}
          width="290"
          height="290"
          alt="uanus"
        />
        <div>
          <h1 className="title">uranus</h1>
          <p className="paragraph">
            Uranus is the seventh planet from the Sun. Its name is a reference
            to the Greek god of the sky, Uranus according to Greek mythology,
            was the great-grandfather of Ares. It has the third-largest
            planetary radius and fourth-largest planetary mass in the Solar
            System.
          </p>
          <span className="source">
            Source :{' '}
            <a
              href="https://en.wikipedia.org/wiki/Uranus"
              rel="noopener noreferrer"
              target="_blank"
            >
              Wikipedia
              <i className="sourceIcon" />
            </a>
          </span>
          <div css={buttonsStyles}>
            <button>
              <span className="number">01</span>
              <span className={spartanBold.className}>overview</span>
            </button>
            <button>
              <span className="number">02</span>
              <span className={spartanBold.className}>internal structure</span>
            </button>
            <button>
              <span className="number">03</span>
              <span className={spartanBold.className}>surface geology</span>
            </button>
          </div>
          <div css={cardsStyles}>
            <div className="card">
              <h4>rotation time</h4>
              <h2>17.2 Hours</h2>
            </div>
            <div className="card">
              <h4>revolution time</h4>
              <h2>84 Years</h2>
            </div>
            <div className="card">
              <h4>radius</h4>
              <h2>25,362 KM</h2>
            </div>
            <div className="card">
              <h4>average temp.</h4>
              <h2>-195°c</h2>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
